name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22.3"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "latest"
          args: --out-format=colored-line-number --timeout=5m
