name: lint-and-test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.3"
          cache: false
      - name: Install dependencies
        run: go get .
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "latest"
      - name: go test
        run: go test -v ./...
